### ISSUE TITLE
Prefill does not work with React Hook Form

### ISSUE THREAD

**Issue by jayeshShelarCandorworks** [goveo/react-international-phone#107]
I am using PhoneInput with React Hook Form as follows:
![image](https://github.com/goveo/react-international-phone/assets/104509042/febd0b52-efc9-47bc-b63f-4b9f661d3d0b)
![image](https://github.com/goveo/react-international-phone/assets/104509042/4d758475-6b80-4467-8c14-c1aa83727bc0)

When I am editing my form I want the field to get prepopulated with previous value. For that I am using react hook form's setValue Method: 
![image](https://github.com/goveo/react-international-phone/assets/104509042/58eb2e29-395e-4d1b-9643-221f57829b40)

If my previous value is Indian phone number it gets prepopulated but if its other than Indian phone number it does not get prepopulated.

Please provide solution for this. Thanks!

**Comment by Eunanibus** [comment]
This is an issue with the way you're setting defaults on `react-hook-form` rather than an issue with this library. 

The Controller is likely a nested child child but the nested child `Controller` registers the field after you set the default values.

Instead, change `defaultValues` to use the response data rather than trying to set the value manually before the field is registered. See [this SO flow post](https://stackoverflow.com/questions/59526726/react-hook-forms-setvalue-method-is-not-working-if-input-is-in-material-ui-dial) here for a more detailed explanation.

**Comment by jayeshShelarCandorworks** [comment]
@Eunanibus I will try that. Thanks!

**Comment by goveo** [comment]
I will close this issue, feel free to reopen it if anything is wrong.
