### ISSUE TITLE
MUI Design - Causes text formatter not to work

### ISSUE THREAD

**Issue by pymenow** [goveo/react-international-phone#132]
**Describe the bug**
I have the code example for Material UI from https://react-international-phone.vercel.app/docs/Advanced%20Usage/useWithUiLibs
However on my setup , the text formater doesnt work .
This seems MUI specific and I havent deviated from the MUI example above.

Except updating this code for FlagImage
              value={country}
              onChange={(e) => setCountry(e.target.value)}
              renderValue={(value) => (
                <FlagImage iso2={value.iso2} style={{ display: 'flex' }} />
              )}
            >

**Comment by goveo** [comment]
@pymenow
Yeah, the JSX example was incorrect, it's already updated, you can check it by the [same link](https://react-international-phone.vercel.app/docs/Advanced%20Usage/useWithUiLibs)
`inputValue` should be displayed as TextField's value prop instead of `phone`

Feel free to reply here if something is wrong.

⭐ Consider leaving a star on this repo if you like the project. Thanks!
