### ISSUE TITLE
country code clash for the Russia and Kazakhstan 

### ISSUE THREAD

**Issue by onlyreddy** [goveo/react-international-phone#46]
Hi,

Recently I'm trying the validation with the `usePhoneValidation `hook and got to know that it's returning false for Russia. After the initial investigation, I found an interesting thing both **Russia** and **Kazakhstan** share the same code as **'7'**, with that the validation is failing and the country is not updating. I tried in your storybook also and found the same.  I also checked the country's data and found both are the same. 

![image](https://user-images.githubusercontent.com/16205943/227553436-24ee7d0d-bec6-40ab-9ace-ccad75ceff4b.png)

![image](https://user-images.githubusercontent.com/16205943/227553550-537cab02-f9ae-4a30-88ed-52db9d7f4e53.png)

Below is the reason for it, which was found in Google. 

![image](https://user-images.githubusercontent.com/16205943/227552810-c848ee4c-c669-48b2-a895-09275f53f756.png)

Can you please update that change?

**Comment by onlyreddy** [comment]
Any update ?

**Comment by goveo** [comment]
It turns out that this is not so easy to fix.
I already found a workaround for this, I think I will be able to release a fix before the end of the week.

**Comment by I-Atlas** [comment]
@goveo, find another issue with false isValid with USA number like +1 (424) ...-....

**Comment by goveo** [comment]
The issue was fixed in v2.2.0
The validation logic was slightly changed. Check the updated [Phone Validation](https://react-international-phone-docs.vercel.app/docs/Usage/PhoneValidation) doc, and [Migration](https://react-international-phone-docs.vercel.app/docs/Migrations/migrate-to-v2.2) doc if you want to keep validation strict as it was before this fix.
